### ISSUE TITLE
Blank issuse when no image is available

### ISSUE THREAD

**Issue by pavansingoji** [yuriy-budiyev/image-loader#1]
When there is no image available on server,
.errorDrawable(new ColorDrawable(R.drawable.error))

error Drawable is working only when some size is specified
 .size(100, 100)

But is size is specified the screen is taking time to load the images.
Can you provide a solution to resolve this

**Comment by yuriy-budiyev** [comment]
new ColorDrawable(R.drawable.error) - use context.getDrawable(R.drawable.error)
